################################################################################
# XDG Base Directory standard paths
################################################################################

XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state

################################################################################
# Per-Application overrides to get them to use proper XDG base dir locations
#
# I like to keep my $HOME fairly clean, but many apps don't respect the XDG
# base dir spec locations and instead place their config/state/cache files
# directly in the home directory. Luckily, most apps do expose app-specific
# overrides via env vars that tell them where their config should be. We define
# those here.
#
# Tip: You can use `xdg-ninja`, which is a CLI too that helps you find out
# whether an application supports such an override, and how to set it.
################################################################################

GNUPGHOME="$XDG_DATA_HOME/gnupg"
