#! /bin/sh

# -------- CONFIG --------
bspc rule -r "*"

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# -------- RULES -------

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Discord desktop='^4'
bspc rule -a Stremio desktop='^6'

bspc rule -a Qalculate-gtk state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# -------- MONITORS --------

# The postswitch script in autorandr automatically handles
# setting and distributing workspaces across monitors. It alsso
# spins up lemonbar on all monitors.
autorandr -c &
