# Use the resolvers below for ordinary DNS lookups.
#
# The configured ~. route in Domains config prevents DHCP DNS from a default
# route interface from becoming a generic default resolver.
#
# Resolved will still use the DNS servers advertised by the connections
# that define DNS domains (via split DNS), if the advertised domains are
# more specific domain over the default ~. route that we configure.
# (such as ~company.example).
#
# We use this approach because new NetworkManager profiles cannot default to rejecting
# advertised DNS by default (while letting some connections override it):
# <https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/work_items/2028>
# If this issue gets fixed, we can consider moving to setting FallbackDNS instead of DNS,
# and relying on that config to prevent any arbitrary untrusted connection from overriding
# the preferred system DNS, while letting some connections that are specifically allowed
# to use automatic DNS take over as the default resolver.
[Resolve]
DNS=9.9.9.9#dns.quad9.net 2620:fe::9#dns.quad9.net 1.1.1.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com
Domains=~.
DNSOverTLS=opportunistic
