#!/bin/sh

# xinitrc runs automatically when startx is ran

# There are some important commands that need to be executed when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is ran automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/config}/x11/xprofile" ]; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    source "$HOME/.xprofile"
fi

exec xmonad

