#!/bin/bash

# This file runs when a DM logs you into a graphical session
# if you use startx/xinit this file should also be soruced.

# Set monitor order
xrandr --output HDMI-1 --auto --output eDP-1 --right-of HDMI-1 --auto &

# Start xsecurelock lockscreen with xss-lock
~/.local/bin/scripts/lockscreen start &

# Set the background with a custom `setbg` script
setbg &

# Use xresources file in ~/.config/x11
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

# Start compositor manager to allow transparency
picom -b --experimental-backends &

# Dunst for notifications
dunst &

# Run network manager applet to show connectivity
nm-applet &

# Run trayer-srg for systemtray bar
# if installed normally, command will be `trayer`, not `trayer-srg` command
trayer --monitor 0 --edge top --align right --widthtype request --padding 0 --transparent true --tint 0x282c34 --alpha 0 --height 23 &

# Start flameshot in background
flameshot &

# AppArmor notifications
aa-notify -p &

# Enable numlock with numlockx
numlockx &

# Udiskie for simple mounting and notifications, no automount for security reasons
udiskie -A -s &

# Enable running applications from chroot
xhost +local:

# Change x shaped default cursor (fonts are located in /usr/include/X11/cursorfont.h)
xsetroot -cursor_name left_ptr
