#!/bin/sh
exec tail -n +3 $0

# Setup GRUB credentials so that it isn't possible for anyone to change the
# boot parameters or use the command line, unless they know user/password pair
#set superusers="admin"
#password admin [unsafe plaintext password]
#password_pbkdf2 admin [safe grub-mkpasswd-pbkdf2 password]


# Make OS Entries unrestricted, so that they can be booted into without prompting
# for user/password pair set above
#menuentry_id_option="--unrestricted $menuentry_id_option"
